version: '3'

services:
  db:
    container_name: test
    image: mysql
    ports:
      - 3308:3306
    volumes:
      - ./mysqldump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=direct
      - MYSQL_USER=directus
      - MYSQL_PASSWORD=171726
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--default-authentication-plugin=mysql_native_password']

  app:
    container_name: directus
    depends_on:
      - db
    image: directus/directus
    restart: unless-stopped
    ports:
      - 8805:8805
    links:
      - db:mysql
    environment:
      - DB_CLIENT=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=direct
      - DB_USER=directus
      - DB_PASSWORD=171726
      - KEY=Hello
      - SECRET=Bye